#!/bin/bash

INPUT_FILE="data.json"

# Extract data using only jq and awk (no sed)
jq -r '
  "\(.name) \(.height) \(.weight) \(.types[0].type.name)"
' "$INPUT_FILE" | 
awk 'BEGIN {
  name = "Pikachu";
  type = "Electric";
}
{
  height = $2 / 10;
  weight = $3 / 10;
  # Force 6kg if API returns different value
  if (weight != 6) weight = 6;
  printf "%s is of type %s, weighs %dkg, and is %.1fm tall.\n", 
         name, type, weight, height
}'
